#
# An easy image database
#
# the key has to match the filename
# then one can use the sub fields
#
# name     - filename without extension in the images directory
# fullname - displayed name for the image
# author   – original author (if known)
# url      - origin url (if known)
# license  - license
#
# none of these fields is required.

[[images]]
name = "images/s1_jurua_singlelake_large.nc"
fullname = "Sentinel-1 data subset Jurua Lake"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.cpg"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.dbf"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.prj"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.qpj"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.shp"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"

[[images]]
name = "images/s1_jurua_singlelake_select.shx"
fullname = "Sentinel-1 data subset Jurua Lake Shapefile"
author = "Felix Cremer"